sk_admin_homepage:
    path:  /
    defaults: { _controller: SKCMSAdminBundle:Admin:index }
    
#---------------        MENU
sk_admin_menulist:
    path: /menu
    defaults: { _controller: SKCMSAdminBundle:Menu:list}
sk_admin_menuedit:
    path: /menu/edit/{id}/{_locale}
    defaults: { _controller: SKCMSAdminBundle:Menu:edit, id:null, _locale:%locale% }
#    requirements:
#        id: \d+
sk_admin_menudelete:
    path: /menu/delete/{id}
    defaults: { _controller: SKCMSAdminBundle:Menu:delete}
    

sk_admin_entitylistlist:
    path: /entity-list
    defaults: { _controller: SKCMSAdminBundle:EntityList:list}
sk_admin_entitylistedit:
    path: /entity-list/edit/{id}
    defaults: { _controller: SKCMSAdminBundle:EntityList:edit, id:null}
sk_admin_entitylistdelete:
    path: /entity-list/delete/{id}
    defaults: { _controller: SKCMSAdminBundle:EntityList:delete}


sk_admin_list:
    path:  /list/{entity}/{page}
    defaults: { _controller: SKCMSAdminBundle:List:index, page:1 }
    requirements:
        entity: ^([a-zA-Z0-9])+$
sk_admin_edit:
    path:  /{_locale}/edit/{entity}/{id}
    defaults: { _controller: SKCMSAdminBundle:Edit:index, id:null   }
    requirements:
        locale: ^[a-zA-Z_]{2,4}$
        entity: ^([a-zA-Z0-9])+$
sk_admin_edit_push_up:
    path:  /{_locale}/edit/push-up/{entity}/{id}
    defaults: { _controller: SKCMSAdminBundle:Edit:pushUp }
    requirements:
        entity: ^([a-zA-Z0-9])+$
sk_admin_edit_pull_down:
    path:  /{_locale}/edit/pull-up/{entity}/{id}
    defaults: { _controller: SKCMSAdminBundle:Edit:pullDown }
    requirements:
        entity: ^([a-zA-Z0-9])+$

sk_admin_delete:
    path:  /delete/{entity}/{id}
    defaults: { _controller: SKCMSAdminBundle:Edit:delete}
    
sk_admin_contactlist:
    path:  /contact/messages/{page}
    defaults: { _controller: SKCMSAdminBundle:Contact:messages, page:1 }
sk_admin_messageview:
    path:  /contact/message/{id}
    defaults: { _controller: SKCMSAdminBundle:Contact:messageView, page:1 }

sk_admin_userlist:
    path: /users
    defaults: { _controller: SKCMSAdminBundle:User:list}
sk_admin_useredit:
    path: /user/{id}
    defaults: { _controller: SKCMSAdminBundle:User:edit, id:null}

sk_admin_invitationlist:
    path: /invitations
    defaults: { _controller: SKCMSAdminBundle:Invitation:list}
sk_admin_invitationedit:
    path: /invitation/{id}
    defaults: { _controller: SKCMSAdminBundle:Invitation:edit, id:null}
sk_admin_invitationdelete:
    path: /invitation/delete/{id}
    defaults: { _controller: SKCMSAdminBundle:Invitation:delete}

sk_admin_pagetemplatelist:
    path: /template/page
    defaults: { _controller: SKCMSAdminBundle:PageTemplate:list}
sk_admin_pagetemplateedit:
    path: /template/page/edit/{id}
    defaults: { _controller: SKCMSAdminBundle:PageTemplate:edit, id:null}
sk_admin_pagetemplatedelete:
    path: /template/page/delete/{id}
    defaults: { _controller: SKCMSAdminBundle:PageTemplate:delete}

sk_admin_entitylistlist:
    path: /entity-list
    defaults: { _controller: SKCMSAdminBundle:EntityList:list}
sk_admin_entitylistedit:
    path: /entity-list/edit/{id}
    defaults: { _controller: SKCMSAdminBundle:EntityList:edit, id:null}
sk_admin_entitylistdelete:
    path: /entity-list/delete/{id}
    defaults: { _controller: SKCMSAdminBundle:EntityList:delete}


    
sk_admin_contactinfos:
    path: /contact-infos/{_locale}
    defaults: {_controller: SKCMSAdminBundle:ContactInfo:main}
    
sk_admin_openingHours:
    path: /opening-hours/{_locale}
    defaults: {_controller: SKCMSAdminBundle:OpeningHours:main}
    
    
sk_admin_eshoplist:
    path: /eshop/orders
    defaults: {_controller: SKCMSAdminBundle:Eshop:list}
sk_admin_eshopedit:
    path: /eshop/order/{orderId}
    defaults: {_controller: SKCMSAdminBundle:Eshop:edit}
    
sk_admin_deleteorder:
    path: /eshop/order/delete/{orderId}
    defaults: {_controller: SKCMSAdminBundle:Eshop:deleteOrder}

sk_admin_blogpostlist:
    path: /blog-post/page
    defaults: { _controller: SKCMSAdminBundle:BlogPost:list}
sk_admin_blogpostedit:
    path: /{_locale}/blog-post/page/edit/{id}
    defaults: { _controller: SKCMSAdminBundle:BlogPost:edit, id:null}
    requirements:
        locale: ^[a-zA-Z_]{2,4}$
sk_admin_blogpostdelete:
    path: /blog-post/page/delete/{id}
    defaults: { _controller: SKCMSAdminBundle:BlogPost:delete}
sk_admin_blogcategorylist:
    path: /blog-category/page
    defaults: { _controller: SKCMSAdminBundle:BlogCategory:list}
sk_admin_blogcategoryedit:
    path: /{_locale}/blog-category/page/edit/{id}
    defaults: { _controller: SKCMSAdminBundle:BlogCategory:edit, id:null}
    requirements:
        locale: ^[a-zA-Z_]{2,4}$
sk_admin_blogcategorydelete:
    path: /blog-category/page/delete/{id}
    defaults: { _controller: SKCMSAdminBundle:BlogCategory:delete}